asp_presentacion/Pages/Ventanas/Brands.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class BrandsModel : PageModel
    {
        private IBrandsPresentacion? iPresentacion = null;

        public BrandsModel(IBrandsPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Brands();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Brands? Actual { get; set; }
        [BindProperty] public Brands? Filtro { get; set; }
        [BindProperty] public List<Brands>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("UserName");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.OriginCountry = Filtro!.OriginCountry ?? "";

                Accion = Enumerables.Ventanas.Listas;

                var task = this.iPresentacion!.PorPais(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Brands();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;

                Task<Brands>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

asp_presentacion/Pages/Ventanas/Categories.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class CategoriesModel : PageModel
    {
        private ICategoriesPresentacion? iPresentacion = null;

        public CategoriesModel(ICategoriesPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Categories();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Categories? Actual { get; set; }
        [BindProperty] public Categories? Filtro { get; set; }
        [BindProperty] public List<Categories>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("UserName");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.CategoryName = Filtro!.CategoryName ?? "";

                Accion = Enumerables.Ventanas.Listas;

                var task = this.iPresentacion!.PorNombre(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Categories();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;

                Task<Categories>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

asp_presentacion/Pages/Ventanas/Customers.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class CustomersModel : PageModel
    {
        private ICustomersPresentacion? iPresentacion = null;

        public CustomersModel(ICustomersPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Customers();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Customers? Actual { get; set; }
        [BindProperty] public Customers? Filtro { get; set; }
        [BindProperty] public List<Customers>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("Usuario");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.Identification = Filtro!.Identification ?? "";

                Accion = Enumerables.Ventanas.Listas;

                var task = this.iPresentacion!.PorIdentificacion(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Customers();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;

                Task<Customers>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

asp_presentacion/Pages/Ventanas/Orders.cshtml.cs
using lib_dominio.Entidades;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;

public class OrdersPageModel : PageModel
{
    private readonly IOrdersPresentacion _ordersPresentacion;

    public OrdersPageModel(IOrdersPresentacion ordersPresentacion)
    {
        _ordersPresentacion = ordersPresentacion;
    }

    [BindProperty(SupportsGet = true)]
    public string? FiltroReferencia { get; set; }

    public List<Orders>? OrdersList { get; set; }

    public async Task OnGetAsync()
    {
        var todasLasOrdenes = await _ordersPresentacion.Listar();

        if (!string.IsNullOrWhiteSpace(FiltroReferencia))
        {
            OrdersList = todasLasOrdenes
                .Where(o => o.OrderRef != null && o.OrderRef.Contains(FiltroReferencia, StringComparison.OrdinalIgnoreCase))
                .ToList();
        }
        else
        {
            OrdersList = todasLasOrdenes;
        }
    }
}

asp_presentacion/Pages/Ventanas/Sales.cshtml.cs
using lib_dominio.Entidades;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace tu_proyecto.Pages
{
    public class SalesModel : PageModel
    {
        private readonly ISalesPresentacion _presentacion;

        public SalesModel(ISalesPresentacion presentacion)
        {
            _presentacion = presentacion;
        }

        [BindProperty]
        public Sales? Filtro { get; set; }

        [BindProperty]
        public List<Sales>? Lista { get; set; }

        public async Task OnGetAsync()
        {
            Lista = await _presentacion.Listar();
        }

        public async Task<IActionResult> OnPostBuscarAsync()
        {
            if (string.IsNullOrWhiteSpace(Filtro?.SaleRef))
            {
                Lista = await _presentacion.Listar();
            }
            else
            {
                Lista = await _presentacion.PorReferencia(Filtro);
            }

            return Page();
        }
    }
}

asp_presentacion/Pages/Ventanas/Vehicles.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using lib_dominio.Entidades;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;

public class VehiclesPageModel : PageModel
{
    private readonly IVehiclesPresentacion _vehiclesPresentacion;

    public VehiclesPageModel(IVehiclesPresentacion vehiclesPresentacion)
    {
        _vehiclesPresentacion = vehiclesPresentacion;
    }

    [BindProperty(SupportsGet = true)]
    public string? FiltroPlaca { get; set; }

    public List<Vehicles>? VehiclesList { get; set; }

    public async Task OnGetAsync()
    {
        if (!string.IsNullOrWhiteSpace(FiltroPlaca))
        {
            VehiclesList = await _vehiclesPresentacion.PorPlaca(new Vehicles { Plate = FiltroPlaca });
        }
        else
        {
            VehiclesList = await _vehiclesPresentacion.Listar();
        }
    }
}

asp_presentacion/Pages/Ventanas/Brands.cshtml
@page
@model asp_presentacion.Pages.Ventanas.BrandsModel
@{
    ViewData["Titulo"] = "Brands";
}
@* <center> *@
@*     <div> *@
@*         <form method="POST" *@
@*               enctype="multipart/form-data"> *@
@*             @Html.AntiForgeryToken() *@

@*             <div align="left"> *@
@*                 <h3>Brands</h3> *@
@*             </div> *@
@*             <div align="left" *@
@*                  class=""> *@
@*                 <input type="submit" *@
@*                        value="Refrescar" *@
@*                        asp-page-handler="BtRefrescar" *@
@*                        class="" *@
@*                        disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" /> *@
@*                 <input type="submit" *@
@*                        value="Nuevo" *@
@*                        asp-page-handler="BtNuevo" *@
@*                        class="" *@
@*                        disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" /> *@
@*                 <input type="submit" *@
@*                        value="Guardar" *@
@*                        asp-page-handler="BtGuardar" *@
@*                        class="" *@
@*                        disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" /> *@
@*                 <input type="submit" *@
@*                        value="Cancelar" *@
@*                        asp-page-handler="BtCancelar" *@
@*                        class="" *@
@*                        disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" /> *@
@*             </div> *@

@*             @if (Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas || *@
@*             Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar) *@
@*             { *@
@*                 <input type="hidden" *@
@*                        asp-for="@Model.Actual!.Id" /> *@
@*             } *@
@*             @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar) *@
@*             { *@
@*                 <input type="hidden" *@
@*                        asp-for="@Model.Actual!.Id" /> *@
@*                 <input type="hidden" *@
@*                        asp-for="@Model.Actual!.BrandName" /> *@
@*                 <input type="hidden" *@
@*                        asp-for="@Model.Actual!.OriginCountry" />                 *@
@*             } *@

@*             @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Editar) *@
@*             { *@
@*                 <div class="containers_vn panel panel-default"> *@
@*                     <h3>Distribuidor</h3> *@

@*                     <div> *@
@*                         <div class="form-group"> *@
@*                             <label class="col-lg-4 control-label"> *@
@*                                 Id *@
@*                             </label> *@
@*                             <div class="col-lg-6"> *@
@*                                 <input id="nmId" *@
@*                                        class="cts_forms form-control" *@
@*                                        asp-for="@Model.Actual!.Id" /> *@
@*                             </div> *@
@*                         </div> *@
@*                         <div class="form-group"> *@
@*                             <label class="col-lg-4 control-label"> *@
@*                                 Nombre *@
@*                             </label> *@
@*                             <div class="col-lg-6"> *@
@*                                 <input id="nmNombre" *@
@*                                        class="cts_forms form-control" *@
@*                                        asp-for="@Model.Actual!.BrandName" /> *@
@*                             </div> *@
@*                         </div> *@
@*                         <div class="form-group"> *@
@*                             <label class="col-lg-4 control-label"> *@
@*                                 Pais de origen *@
@*                             </label> *@
@*                             <div class="col-lg-6"> *@
@*                                 <input id="nmPaisOrigen" *@
@*                                        class="cts_forms form-control" *@
@*                                        asp-for="@Model.Actual!.OriginCountry" /> *@
@*                             </div> *@
@*                         </div> *@
                        
@*                     </div> *@
@*                 </div> *@
@*             } *@

@*             @if (ViewData.ContainsKey("Mensaje")) *@
@*             { *@
@*                 <input type="hidden" *@
@*                        asp-for="@Model.Accion" /> *@
@*                 @await Html.PartialAsync("../Emergentes/Mensajes.cshtml") *@
@*                 ; *@
@*             } *@

@*             @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar) *@
@*             { *@
@*                 <div class='popup'> *@
@*                     <div class='pp_del_inner'> *@
@*                         <div style='width:95%'> *@
@*                             <h2 align="left"> *@
@*                                 Mensaje *@
@*                             </h2> *@

@*                             <h4 align="left"> *@
@*                                 Desea borrar la entidad? *@
@*                             </h4> *@
@*                             <h6 align="left"> *@
@*                                 @Model.Actual!.Id, *@
@*                                 @Model.Actual!.BrandName *@
@*                             </h6> *@
@*                             <br /> *@
@*                             <br /> *@
@*                             <input type="submit" *@
@*                                    value="Borrar" *@
@*                                    asp-page-handler="BtBorrar" *@
@*                                    class="btn btn-secondary" /> *@
@*                             <input type="submit" *@
@*                                    value="Cerrar" *@
@*                                    asp-page-handler="BtCancelar" *@
@*                                    class="btn btn-secondary" /> *@
@*                         </div> *@
@*                     </div> *@
@*                 </div> *@
@*             } *@

@*             @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas || *@
@*             Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar) *@
@*             { *@
@*                 <input id="flCodigo" *@
@*                        class="cts_forms form-control" *@
@*                        asp-for="@Model.Filtro!.OriginCountry" *@
@*                        placeholder="Pais" /> *@
@*                 <br /> *@

@*                 <div class="containers_vn panel panel-default"> *@
@*                     <table class="tb_data table table-striped table-bordered table-hover"> *@
@*                         <tr> *@
@*                             <th> *@
@*                                 Id *@
@*                             </th> *@
@*                             <th> *@
@*                                 Nombre *@
@*                             </th> *@
@*                             <th class="cl_hidden"> *@
@*                                 Pais Origen *@
@*                             </th>                             *@
@*                             <th> *@
@*                                 Accion *@
@*                             </th> *@
@*                         </tr> *@
@*                         @if (Model != null && Model.Lista != null) *@
@*                         { *@
@*                             @foreach (var elemento in Model.Lista) *@
@*                             { *@
@*                                 <tr> *@
@*                                     <td> *@
@*                                         @elemento.Id *@
@*                                     </td> *@
@*                                     <td> *@
@*                                         @elemento.BrandName *@
@*                                     </td> *@
@*                                     <td class="cl_hidden"> *@
@*                                         @elemento.OriginCountry *@
@*                                     </td>                                     *@
@*                                     <td> *@
@*                                         <input type="submit" *@
@*                                                value="Modicar" *@
@*                                                asp-page-handler="BtModificar" *@
@*                                                class="btn btn-secondary" *@
@*                                                asp-route-data="@elemento.Id" /> *@
@*                                         <input type="submit" *@
@*                                                value="Borrar" *@
@*                                                asp-page-handler="BtBorrarVal" *@
@*                                                class="btn btn-secondary" *@
@*                                                asp-route-data="@elemento.Id" /> *@
@*                                     </td> *@
@*                                 </tr> *@
@*                             } *@
@*                         } *@
@*                     </table> *@
@*                 </div> *@
@*             } *@
@*         </form> *@
@*     </div> *@
@* </center> *@

<header>
    <partial name="_Navbar" />
</header>

<div>
    <h1>Funcaaaaaaaaa</h1>

</div>

asp_presentacion/Pages/Ventanas/Orders.cshtml
@page
@model OrdersPageModel

<h1>Órdenes</h1>

<form method="get">
    <div class="form-group">
        <label for="filtro">Buscar por referencia:</label>
        <input type="text" id="filtro" name="FiltroReferencia" value="@Model.FiltroReferencia" class="form-control" />
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
    </div>
</form>

@if (Model.OrdersList?.Any() == true)
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Referencia</th>
                <th>Observación Cliente</th>
                <th>Observación Taller</th>
                <th>Empleado</th>
                <th>Vehículo</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model.OrdersList)
            {
                <tr>
                    <td>@order.Id</td>
                    <td>@order.OrderRef</td>
                    <td>@order.CustomerRemark</td>
                    <td>@order.ServiceCenterRemark</td>
                    <td>@order._Employees?.EmployeeName</td>
                    <td>@order._Vehicle?.Plate</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No hay órdenes disponibles.</p>
}

asp_presentacion/Pages/Ventanas/Sales.cshtml
@page
@model tu_proyecto.Pages.SalesModel
@{
    ViewData["Title"] = "Ventas";
}

<h2>Ventas</h2>

<form method="post" asp-page-handler="Buscar">
    <input asp-for="Filtro.SaleRef" placeholder="Buscar por referencia" />
    <button type="submit">Buscar</button>
</form>

@if (Model.Lista != null && Model.Lista.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Referencia</th>
                <th>Método de Pago</th>
                <th>Total</th>
                <th>Orden ID</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var venta in Model.Lista)
            {
                <tr>
                    <td>@venta.Id</td>
                    <td>@venta.SaleRef</td>
                    <td>@venta._PaymentMethod?.PaymentMethod</td>
                    <td>@venta.Total.ToString("C")</td>
                    <td>@venta.OrderId</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No hay ventas para mostrar.</p>
}

asp_presentacion/Pages/Ventanas/Vehicles.cshtml
@page
@model VehiclesPageModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Vehículos</h1>

<form method="get" class="mb-4">
    <div class="form-group">
        <label for="placa">Buscar por placa:</label>
        <input type="text" id="placa" name="FiltroPlaca" value="@Model.FiltroPlaca" class="form-control" />
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
        <a href="/Vehicles" class="btn btn-secondary mt-2 ms-2">Limpiar</a>
    </div>
</form>

@if (Model.VehiclesList?.Any() == true)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Placa</th>
                <th>Chasis</th>
                <th>Color</th>
                <th>Motor</th>
                <th>Cliente</th>
                <th>Marca</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var vehicle in Model.VehiclesList)
            {
                <tr>
                    <td>@vehicle.Plate</td>
                    <td>@vehicle.Chassis</td>
                    <td>@vehicle.Color</td>
                    <td>@vehicle.Engine</td>
                    <td>@vehicle._Customer?.CustomerName</td>
                    <td>@vehicle._Brand?.BrandName</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No se encontraron vehículos.</p>
}